const data = [
  // {
  //   unit: "102",
  //   name: "taka",
  //   title: "Onishi Apparel",
  //   description: "taka is a fashion designer and artist.",
  //   image: null,
  //   links: [
  //     { title: "@takayuki.us", href: "https://instagram.com/takayuki.us" },
  //     { title: "@onishi.us", href: "https://instagram.com/onishi.us" },
  //   ],
  // },
  {
    unit: "104",
    name: "beau bray",
    title: "Musician",
    description: "beau bray is a musician.",
    image: null,
    links: [{ title: "@beaubray", href: "https://instagram.com/beaubray" }, { title: "beaubray.com", href: "https://beaubray.com" }],
  },
  {
    unit: "107",
    name: "Danielle Armstrong",
    title: "Prop styling / photography",
    description: "Prop styling / photography",
    image: null,
    links: [{ title: "@danielle___armstrong", href: "https://www.instagram.com/danielle___armstrong" }, { title: "daniellestyles.com", href: "https://www.daniellestyles.com" }],
  },
  {
    unit: "110",
    name: "Adam & Suezy",
    title: "crochet, caipirinhas & thrifting",
    description: "Caipirinhas, thrifting and music",
    image: null,
    links: [{ title: "@lilpony666", href: "https://www.instagram.com/lilpony666" }, { title: "@internetritual", href: "https://www.instagram.com/internetritual" }],
  },
  // {
  //   unit: "110",
  //   name: "adam & suezy",
  //   title: "vintage clothing & tattoo artist",
  //   description: "adam & suezy are a couple who love vintage clothing and tattoos.",
  //   image: null,
  //   links: [{ title: "website", href: "/melon.webp" }],
  // },
  {
    unit: "114",
    name: "S.A.P. Gallery",
    title: "Mixed Media Artist",
    description:
      "A Group Art show with mixed themes and materials featuring Artists Michael Schmidt, S.A.P., Ari Nichole, Nick Runge, Enrique Becerra, Elliott Giffis and other fun Goodies",
    image: "/artist/sap.jpg",
    links: [
      { title: "superapplepieartgallery.com", href: "https://www.superapplepieartgallery.com" },
      { title: "@superapplepiegallery", href: "https://instagram.com/superapplepiegallery" },
    ],
  },
  {
    unit: "114",
    name: "Michael Schmidt",
    title: "Photographer",
    description: "",
    image: null,
    links: [{ title: "schmidtphotographer.com", href: "https://www.schmidtphotographer.com/" }],
  },
  {
    unit: "COURTYARD & 114",
    name: "Henry Becerra",
    title: "Stone Sculptor",
    description: "Enrique Barajas Becerra - stone sculptor",
    image: null,
    links: [{ title: "@ebbandstone", href: "https://instagram.com/ebbandstone" }],
  },
  {
    unit: "COURTYARD",
    name: "Sophia Park",
    title: "Food",
    description: "actual sandwiches, to eat!",
    image: null,
    links: [{ title: "@eatwitchies", href: "https://instagram.com/eatwitchies" }],
  },
  {
    unit: "202",
    name: "Jordan Service",
    title: "Photography",
    description: "Queer Photographer",
    image: null,
    links: [{ title: "@jrdsrv", href: "https://instagram.com/jrdsrv" }],
  },
  // {
  //   unit: "203",
  //   name: "perhacs studio",
  //   title: "design",
  //   description: "perhacs studio is a design studio.",
  //   image: null,
  //   links: [{ title: "@perhacs.studios", href: "https://instagram/perhacs.studios" }],
  // },
  {
    unit: "204",
    name: "Saiful Haque",
    title: "Artist",
    description: "Artist born Dhaka Bangladesh. Notable clients: Disney, Google, Apple, Riot Games, Avatar, NEOM",
    image: null,
    links: [{ title: "@saiful.haque", href: "https://instagram.com/saiful.haque" }],
  },
  // {
  //   unit: "205",
  //   name: "Sarah Lew",
  //   title: "Puppet Mistress",
  //   description: "",
  //   image: "artist/205/1.jpeg",
  //   links: [{ title: "@dumbbabyofficial", href: "https://instagram.com/dumbbabyofficial" }],
  // },
  {
    unit: "209",
    name: "Prey Taxidermy",
    title: "Taxidermy Studio",
    description: "Prey Taxidermy specializes in the creation of taxidermy for museums & nature centers. We also teach taxidermy workshops and create artistic commissions.",
    image: null,
    links: [{ title: "PreyTaxidermy.com", href: "https://PreyTaxidermy.com" }],
  },
  // {
  //   unit: "212",
  //   name: "montana bertoletti",
  //   title: "Mixed Media Artist",
  //   description:
  //     "At loft 212 you’ll find a collection of mixed media collage art which is made through a process of photography, printing and painting on canvas, wood and other materials. </br></br> You’ll also see multiple video projections of stop motion animations. Some are stand alone pieces and others were made specifically for musicians. </br></br> There will be prints of selected art pieces available for $10.",
  //   image: "artist/montana-bertoletti/montana.jpeg",
  //   links: [{ title: "@themontanagram", href: "https://instagram.com/themontanagram" }],
  // },
  {
    unit: "210",
    name: "Jae Seung Lee",
    title: "Fashion / Vintage Shop",
    description: "TWO FOLD is a vintage clothing store and brand based in Los Angeles, California",
    image: null,
    links: [
      { title: "@jaeseung_lee_", href: "https://www.instagram.com/jaeseung_lee_" },
      { title: "@twofold_la", href: "https://instagram.com/twofold_la" },
    ],
  },
  {
    unit: "213",
    name: "Adam Matano",
    title: "Contemporary Representational Artist",
    description: "Adam Matano is a contemporary representational artist who specializes in sculpture. His artistic practice is characterized by an organic evolution, integrating a visceral response to life with a deep appreciation for the natural world and humanity's connection to it.",
    image: null,
    links: [{ title: "adammatano.com", href: "https://adammatano.com" }, { title: "@adammatanosculpture", href: "https://www.instagram.com/adammatanosculpture" }],
  },
  {
    unit: "215",
    name: "Workplace Romance",
    title: "Workplace Romance",
    description: "Workplace Romance is the collaborative rug studio of Rachel Shin and Revel Rosa. Each hand-tufted piece is designed and made once, one of one, never again. Made for eclectic homes and the people who shape them.",
    image: null,
    links: [{ title: "workplaceromancethebrand.com", href: "https://workplaceromancethebrand.com" }],
  },
  {
    unit: "219",
    name: "Katie Goodfellow",
    title: "Stylist and costume designer",
    description: "Stylist and costume designer selling vintage and handmade knitwear!",
    image: null,
    links: [{ title: "katiegoodfellow.com", href: "https://www.katiegoodfellow.com" }],
  },
  {
    unit: "221",
    name: "sion kim & justin yook",
    title: "sion kim & justin yook",
    description: "Collective of young creatives sharing what they love to others to enjoy!",
    image: null,
    links: [
      { title: "@kim.yayy", href: "https://instagram.com/kim.yayy" },
      { title: "@yook.noir", href: "https://instagram.com/yook.noir" },
      { title: "@sogum.xyz", href: "https://instagram.com/sogum.xyz" },
      { title: "@zookidkrule", href: "https://instagram.com/zookidkrule" },
      { title: "@lleejjeanne", href: "https://instagram.com/lleejjeanne" },
      { title: "@sydneytsay", href: "https://instagram.com/sydneytsay" },
      { title: "@obvlee", href: "https://instagram.com/obvlee" },
    ],
  },
  {
    unit: "301",
    name: "Frank Irving",
    title: "Stock market day trader / Mentor",
    description: "",
    image: null,
    links: [{ title: "@panchinilive", href: "https://www.tiktok.com/@panchinilive" }],
  },
  {
    unit: "304",
    name: "Joshua Ballinger",
    title: "Filmaker/Photographer",
    description:
      "Photo/video studio. Documenting the Light is the Film and Photography work of Joshua Ballinger. Joshua fancies himself an artist, and considers photography his first medium: A tool that taught him as much about himself as the world around him.",
    image: "artist/documenting-the-light/1.jpeg",
    links: [
      {
        title: "documentingthelight.com",
        href: "https://www.documentingthelight.com",
      },
      { title: "@documentingthelight", href: "https://instagram.com/documentingthelight" },
    ],
  },
  {
    unit: "305&306",
    name: "nate fu",
    title: "Production Studio",
    description: "Creative space for video and art",
    image: null,
    links: [{ title: "msrobot.com", href: "https://www.msrobot.com" }, { title: "@ms_robot", href: "https://instagram.com/ms_robot" }],
  },
];

export default data;
