const data = [
  {
    unit: "102",
    name: "taka",
    title: "onishi apparel",
    description: "taka is a fashion designer and artist.",
    image: null,
    links: [{ title: "website", href: "/melon.webp" }],
  },
  {
    unit: "104",
    name: "beau bray",
    title: "musician",
    description: "beau bray is a musician.",
    image: null,
    links: [{ title: "website", href: "/melon.webp" }],
  },
  {
    unit: "109",
    name: "ariel klevecz",
    title: "interactive art",
    description:
      "ariel klevecz is an interactive artist who creates installations and performances. He is interested in the intersection of art and technology. He is a member of the art collective, the lab. He is also a member of the art collective, the lab.",
    image: "/artist/bao-scientist.png",
    links: [{ title: "yaytso.art", href: "https://yaytso.art" }],
  },
  // {
  //   unit: "110",
  //   name: "adam & suezy",
  //   title: "vintage clothing & tattoo artist",
  //   description: "adam & suezy are a couple who love vintage clothing and tattoos.",
  //   image: null,
  //   links: [{ title: "website", href: "/melon.webp" }],
  // },
  {
    unit: "114",
    name: "S.A.P. Gallery",
    title: "mixed media artist",
    description:
      "Welcome Super Apple Pie Gallery, Join us for an evening of diverse artistic expression. This group art show features a captivating mix of photography, paintings, and handmade clothing, exploring a range of adult themes. Experience a unique blend of creativity and craftsmanship, and engage with thought-provoking works that challenge and inspire. Don’t miss this opportunity to immerse yourself in an eclectic and dynamic collection of art. featuring artists",
    image: "/artist/sap.jpg",
    links: [
      { title: "superapplepieartgallery.com", href: "https://www.superapplepieartgallery.com" },
      { title: "@superapplepiegallery", href: "https://instagram.com/superapplepiegallery" },
      { title: "@divalicious", href: "https://instagram.com/divalicious" },
      { title: "@arinicholeartisty", href: "https://instagram.com/arinicholeartisty" },
      { title: "@nickvrunge", href: "https://instagram.com/nickvrunge" },
      { title: "@elliottevan", href: "https://instagram.com/elliottevan" },
    ],
  },
  {
    unit: "202",
    name: "jordan service",
    title: "photography",
    description: "jordan service is a photographer.",
    image: null,
    links: [{ title: "website", href: "/melon.webp" }],
  },
  {
    unit: "203",
    name: "perhacs studio",
    title: "design",
    description: "perhacs studio is a design studio.",
    image: null,
    links: [{ title: "website", href: "/melon.webp" }],
  },
  {
    unit: "204",
    name: "saiful haque",
    title: "artist",
    description: "saiful haque is an artist.",
    image: null,
    links: [{ title: "website", href: "/melon.webp" }],
  },
  {
    unit: "205",
    name: "swardy & sarah",
    title: "puppetry & music",
    description: "sarah is a puppet master. swardy is a musician.",
    image: null,
    links: [{ title: "website", href: "/melon.webp" }],
  },
  {
    unit: "209",
    name: "paloma pajaro prey taxidermy",
    title: "taxidermy studio",
    description: "paloma pajaro is a taxidermist.",
    image: null,
    links: [{ title: "website", href: "/melon.webp" }],
  },
  {
    unit: "212",
    name: "montana bertoletti",
    title: "mixed media art/stop motion",
    description: "montana bertoletti is a mixed media artist.",
    image: null,
    links: [{ title: "website", href: "/melon.webp" }],
  },
  {
    unit: "221",
    name: "sion kim",
    title: "tattoo artist",
    description: "I draw on people and bring invisible thoughts to visible expressions.",
    image: null,
    links: [
      { title: "@kim.yayy", href: "https://instagram.com/kim.yayy" },
      { title: "nomadicvision.studio", href: "https://nomadicvision.studio" },
    ],
  },
  {
    unit: "306305",
    name: "ms robot",
    title: "production studio",
    description: "ms robot is a production studio.",
    image: null,
    links: [{ title: "website", href: "/melon.webp" }],
  },
];

export default data;
